FROM node:25-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm config set fetch-retry-maxtimeout 600000 && \
    npm config set fetch-retry-mintimeout 100000 && \
    npm install --omit=dev --no-audit --no-fund

# Copy source code
COPY src/bot ./src/bot
COPY prisma ./prisma

# Generate Prisma Client
RUN npx prisma generate

# Run the bot
CMD ["./node_modules/.bin/tsx", "src/bot/index.ts"]
